/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BfhlRouteImport } from './routes/bfhl'
import { Route as IndexRouteImport } from './routes/index'

const BfhlRoute = BfhlRouteImport.update({
  id: '/bfhl',
  path: '/bfhl',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bfhl': typeof BfhlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bfhl': typeof BfhlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bfhl': typeof BfhlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bfhl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bfhl'
  id: '__root__' | '/' | '/bfhl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BfhlRoute: typeof BfhlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bfhl': {
      id: '/bfhl'
      path: '/bfhl'
      fullPath: '/bfhl'
      preLoaderRoute: typeof BfhlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BfhlRoute: BfhlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
